/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.banking.server;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2020-02-04")
public class TManagerService {

  public interface Iface {

    public String addCustomer(String customerAccountNumber, String managerAccountNumber) throws TException;

    public String removeCustomer(String accountNumber) throws TException;

    public String deposit(String accountNumber, double amount) throws TException;

  }

  public interface AsyncIface {

    public void addCustomer(String customerAccountNumber, String managerAccountNumber, AsyncMethodCallback resultHandler) throws TException;

    public void removeCustomer(String accountNumber, AsyncMethodCallback resultHandler) throws TException;

    public void deposit(String accountNumber, double amount, AsyncMethodCallback resultHandler) throws TException;

  }

  public static class Client extends org.apache.thrift.TServiceClient implements Iface {
    public static class Factory implements org.apache.thrift.TServiceClientFactory<Client> {
      public Factory() {}
      public Client getClient(org.apache.thrift.protocol.TProtocol prot) {
        return new Client(prot);
      }
      public Client getClient(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
        return new Client(iprot, oprot);
      }
    }

    public Client(org.apache.thrift.protocol.TProtocol prot)
    {
      super(prot, prot);
    }

    public Client(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
      super(iprot, oprot);
    }

    public String addCustomer(String customerAccountNumber, String managerAccountNumber) throws TException
    {
      send_addCustomer(customerAccountNumber, managerAccountNumber);
      return recv_addCustomer();
    }

    public void send_addCustomer(String customerAccountNumber, String managerAccountNumber) throws TException
    {
      addCustomer_args args = new addCustomer_args();
      args.setCustomerAccountNumber(customerAccountNumber);
      args.setManagerAccountNumber(managerAccountNumber);
      sendBase("addCustomer", args);
    }

    public String recv_addCustomer() throws TException
    {
      addCustomer_result result = new addCustomer_result();
      receiveBase(result, "addCustomer");
      if (result.isSetSuccess()) {
        return result.success;
      }
      throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "addCustomer failed: unknown result");
    }

    public String removeCustomer(String accountNumber) throws TException
    {
      send_removeCustomer(accountNumber);
      return recv_removeCustomer();
    }

    public void send_removeCustomer(String accountNumber) throws TException
    {
      removeCustomer_args args = new removeCustomer_args();
      args.setAccountNumber(accountNumber);
      sendBase("removeCustomer", args);
    }

    public String recv_removeCustomer() throws TException
    {
      removeCustomer_result result = new removeCustomer_result();
      receiveBase(result, "removeCustomer");
      if (result.isSetSuccess()) {
        return result.success;
      }
      throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "removeCustomer failed: unknown result");
    }

    public String deposit(String accountNumber, double amount) throws TException
    {
      send_deposit(accountNumber, amount);
      return recv_deposit();
    }

    public void send_deposit(String accountNumber, double amount) throws TException
    {
      deposit_args args = new deposit_args();
      args.setAccountNumber(accountNumber);
      args.setAmount(amount);
      sendBase("deposit", args);
    }

    public String recv_deposit() throws TException
    {
      deposit_result result = new deposit_result();
      receiveBase(result, "deposit");
      if (result.isSetSuccess()) {
        return result.success;
      }
      throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "deposit failed: unknown result");
    }

  }
  public static class AsyncClient extends org.apache.thrift.async.TAsyncClient implements AsyncIface {
    public static class Factory implements org.apache.thrift.async.TAsyncClientFactory<AsyncClient> {
      private org.apache.thrift.async.TAsyncClientManager clientManager;
      private org.apache.thrift.protocol.TProtocolFactory protocolFactory;
      public Factory(org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.protocol.TProtocolFactory protocolFactory) {
        this.clientManager = clientManager;
        this.protocolFactory = protocolFactory;
      }
      public AsyncClient getAsyncClient(org.apache.thrift.transport.TNonblockingTransport transport) {
        return new AsyncClient(protocolFactory, clientManager, transport);
      }
    }

    public AsyncClient(org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.transport.TNonblockingTransport transport) {
      super(protocolFactory, clientManager, transport);
    }

    public void addCustomer(String customerAccountNumber, String managerAccountNumber, AsyncMethodCallback resultHandler) throws TException {
      checkReady();
      addCustomer_call method_call = new addCustomer_call(customerAccountNumber, managerAccountNumber, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class addCustomer_call extends org.apache.thrift.async.TAsyncMethodCall {
      private String customerAccountNumber;
      private String managerAccountNumber;
      public addCustomer_call(String customerAccountNumber, String managerAccountNumber, AsyncMethodCallback resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.customerAccountNumber = customerAccountNumber;
        this.managerAccountNumber = managerAccountNumber;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("addCustomer", org.apache.thrift.protocol.TMessageType.CALL, 0));
        addCustomer_args args = new addCustomer_args();
        args.setCustomerAccountNumber(customerAccountNumber);
        args.setManagerAccountNumber(managerAccountNumber);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public String getResult() throws TException {
        if (getState() != State.RESPONSE_READ) {
          throw new IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_addCustomer();
      }
    }

    public void removeCustomer(String accountNumber, AsyncMethodCallback resultHandler) throws TException {
      checkReady();
      removeCustomer_call method_call = new removeCustomer_call(accountNumber, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class removeCustomer_call extends org.apache.thrift.async.TAsyncMethodCall {
      private String accountNumber;
      public removeCustomer_call(String accountNumber, AsyncMethodCallback resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.accountNumber = accountNumber;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("removeCustomer", org.apache.thrift.protocol.TMessageType.CALL, 0));
        removeCustomer_args args = new removeCustomer_args();
        args.setAccountNumber(accountNumber);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public String getResult() throws TException {
        if (getState() != State.RESPONSE_READ) {
          throw new IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_removeCustomer();
      }
    }

    public void deposit(String accountNumber, double amount, AsyncMethodCallback resultHandler) throws TException {
      checkReady();
      deposit_call method_call = new deposit_call(accountNumber, amount, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class deposit_call extends org.apache.thrift.async.TAsyncMethodCall {
      private String accountNumber;
      private double amount;
      public deposit_call(String accountNumber, double amount, AsyncMethodCallback resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.accountNumber = accountNumber;
        this.amount = amount;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("deposit", org.apache.thrift.protocol.TMessageType.CALL, 0));
        deposit_args args = new deposit_args();
        args.setAccountNumber(accountNumber);
        args.setAmount(amount);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public String getResult() throws TException {
        if (getState() != State.RESPONSE_READ) {
          throw new IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_deposit();
      }
    }

  }

  public static class Processor<I extends Iface> extends org.apache.thrift.TBaseProcessor<I> implements org.apache.thrift.TProcessor {
    private static final Logger LOGGER = LoggerFactory.getLogger(Processor.class.getName());
    public Processor(I iface) {
      super(iface, getProcessMap(new HashMap<String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>>()));
    }

    protected Processor(I iface, Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends Iface> Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> getProcessMap(Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      processMap.put("addCustomer", new addCustomer());
      processMap.put("removeCustomer", new removeCustomer());
      processMap.put("deposit", new deposit());
      return processMap;
    }

    public static class addCustomer<I extends Iface> extends org.apache.thrift.ProcessFunction<I, addCustomer_args> {
      public addCustomer() {
        super("addCustomer");
      }

      public addCustomer_args getEmptyArgsInstance() {
        return new addCustomer_args();
      }

      protected boolean isOneway() {
        return false;
      }

      public addCustomer_result getResult(I iface, addCustomer_args args) throws TException {
        addCustomer_result result = new addCustomer_result();
        result.success = iface.addCustomer(args.customerAccountNumber, args.managerAccountNumber);
        return result;
      }
    }

    public static class removeCustomer<I extends Iface> extends org.apache.thrift.ProcessFunction<I, removeCustomer_args> {
      public removeCustomer() {
        super("removeCustomer");
      }

      public removeCustomer_args getEmptyArgsInstance() {
        return new removeCustomer_args();
      }

      protected boolean isOneway() {
        return false;
      }

      public removeCustomer_result getResult(I iface, removeCustomer_args args) throws TException {
        removeCustomer_result result = new removeCustomer_result();
        result.success = iface.removeCustomer(args.accountNumber);
        return result;
      }
    }

    public static class deposit<I extends Iface> extends org.apache.thrift.ProcessFunction<I, deposit_args> {
      public deposit() {
        super("deposit");
      }

      public deposit_args getEmptyArgsInstance() {
        return new deposit_args();
      }

      protected boolean isOneway() {
        return false;
      }

      public deposit_result getResult(I iface, deposit_args args) throws TException {
        deposit_result result = new deposit_result();
        result.success = iface.deposit(args.accountNumber, args.amount);
        return result;
      }
    }

  }

  public static class AsyncProcessor<I extends AsyncIface> extends org.apache.thrift.TBaseAsyncProcessor<I> {
    private static final Logger LOGGER = LoggerFactory.getLogger(AsyncProcessor.class.getName());
    public AsyncProcessor(I iface) {
      super(iface, getProcessMap(new HashMap<String, org.apache.thrift.AsyncProcessFunction<I, ? extends org.apache.thrift.TBase, ?>>()));
    }

    protected AsyncProcessor(I iface, Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends AsyncIface> Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase,?>> getProcessMap(Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      processMap.put("addCustomer", new addCustomer());
      processMap.put("removeCustomer", new removeCustomer());
      processMap.put("deposit", new deposit());
      return processMap;
    }

    public static class addCustomer<I extends AsyncIface> extends org.apache.thrift.AsyncProcessFunction<I, addCustomer_args, String> {
      public addCustomer() {
        super("addCustomer");
      }

      public addCustomer_args getEmptyArgsInstance() {
        return new addCustomer_args();
      }

      public AsyncMethodCallback<String> getResultHandler(final AsyncFrameBuffer fb, final int seqid) {
        final org.apache.thrift.AsyncProcessFunction fcall = this;
        return new AsyncMethodCallback<String>() { 
          public void onComplete(String o) {
            addCustomer_result result = new addCustomer_result();
            result.success = o;
            try {
              fcall.sendResponse(fb,result, org.apache.thrift.protocol.TMessageType.REPLY,seqid);
              return;
            } catch (Exception e) {
              LOGGER.error("Exception writing to internal frame buffer", e);
            }
            fb.close();
          }
          public void onError(Exception e) {
            byte msgType = org.apache.thrift.protocol.TMessageType.REPLY;
            org.apache.thrift.TBase msg;
            addCustomer_result result = new addCustomer_result();
            {
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = (org.apache.thrift.TBase)new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.INTERNAL_ERROR, e.getMessage());
            }
            try {
              fcall.sendResponse(fb,msg,msgType,seqid);
              return;
            } catch (Exception ex) {
              LOGGER.error("Exception writing to internal frame buffer", ex);
            }
            fb.close();
          }
        };
      }

      protected boolean isOneway() {
        return false;
      }

      public void start(I iface, addCustomer_args args, AsyncMethodCallback<String> resultHandler) throws TException {
        iface.addCustomer(args.customerAccountNumber, args.managerAccountNumber,resultHandler);
      }
    }

    public static class removeCustomer<I extends AsyncIface> extends org.apache.thrift.AsyncProcessFunction<I, removeCustomer_args, String> {
      public removeCustomer() {
        super("removeCustomer");
      }

      public removeCustomer_args getEmptyArgsInstance() {
        return new removeCustomer_args();
      }

      public AsyncMethodCallback<String> getResultHandler(final AsyncFrameBuffer fb, final int seqid) {
        final org.apache.thrift.AsyncProcessFunction fcall = this;
        return new AsyncMethodCallback<String>() { 
          public void onComplete(String o) {
            removeCustomer_result result = new removeCustomer_result();
            result.success = o;
            try {
              fcall.sendResponse(fb,result, org.apache.thrift.protocol.TMessageType.REPLY,seqid);
              return;
            } catch (Exception e) {
              LOGGER.error("Exception writing to internal frame buffer", e);
            }
            fb.close();
          }
          public void onError(Exception e) {
            byte msgType = org.apache.thrift.protocol.TMessageType.REPLY;
            org.apache.thrift.TBase msg;
            removeCustomer_result result = new removeCustomer_result();
            {
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = (org.apache.thrift.TBase)new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.INTERNAL_ERROR, e.getMessage());
            }
            try {
              fcall.sendResponse(fb,msg,msgType,seqid);
              return;
            } catch (Exception ex) {
              LOGGER.error("Exception writing to internal frame buffer", ex);
            }
            fb.close();
          }
        };
      }

      protected boolean isOneway() {
        return false;
      }

      public void start(I iface, removeCustomer_args args, AsyncMethodCallback<String> resultHandler) throws TException {
        iface.removeCustomer(args.accountNumber,resultHandler);
      }
    }

    public static class deposit<I extends AsyncIface> extends org.apache.thrift.AsyncProcessFunction<I, deposit_args, String> {
      public deposit() {
        super("deposit");
      }

      public deposit_args getEmptyArgsInstance() {
        return new deposit_args();
      }

      public AsyncMethodCallback<String> getResultHandler(final AsyncFrameBuffer fb, final int seqid) {
        final org.apache.thrift.AsyncProcessFunction fcall = this;
        return new AsyncMethodCallback<String>() { 
          public void onComplete(String o) {
            deposit_result result = new deposit_result();
            result.success = o;
            try {
              fcall.sendResponse(fb,result, org.apache.thrift.protocol.TMessageType.REPLY,seqid);
              return;
            } catch (Exception e) {
              LOGGER.error("Exception writing to internal frame buffer", e);
            }
            fb.close();
          }
          public void onError(Exception e) {
            byte msgType = org.apache.thrift.protocol.TMessageType.REPLY;
            org.apache.thrift.TBase msg;
            deposit_result result = new deposit_result();
            {
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = (org.apache.thrift.TBase)new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.INTERNAL_ERROR, e.getMessage());
            }
            try {
              fcall.sendResponse(fb,msg,msgType,seqid);
              return;
            } catch (Exception ex) {
              LOGGER.error("Exception writing to internal frame buffer", ex);
            }
            fb.close();
          }
        };
      }

      protected boolean isOneway() {
        return false;
      }

      public void start(I iface, deposit_args args, AsyncMethodCallback<String> resultHandler) throws TException {
        iface.deposit(args.accountNumber, args.amount,resultHandler);
      }
    }

  }

  public static class addCustomer_args implements org.apache.thrift.TBase<addCustomer_args, addCustomer_args._Fields>, java.io.Serializable, Cloneable, Comparable<addCustomer_args>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("addCustomer_args");

    private static final org.apache.thrift.protocol.TField CUSTOMER_ACCOUNT_NUMBER_FIELD_DESC = new org.apache.thrift.protocol.TField("customerAccountNumber", org.apache.thrift.protocol.TType.STRING, (short)1);
    private static final org.apache.thrift.protocol.TField MANAGER_ACCOUNT_NUMBER_FIELD_DESC = new org.apache.thrift.protocol.TField("managerAccountNumber", org.apache.thrift.protocol.TType.STRING, (short)2);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new addCustomer_argsStandardSchemeFactory());
      schemes.put(TupleScheme.class, new addCustomer_argsTupleSchemeFactory());
    }

    public String customerAccountNumber; // required
    public String managerAccountNumber; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      CUSTOMER_ACCOUNT_NUMBER((short)1, "customerAccountNumber"),
      MANAGER_ACCOUNT_NUMBER((short)2, "managerAccountNumber");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // CUSTOMER_ACCOUNT_NUMBER
            return CUSTOMER_ACCOUNT_NUMBER;
          case 2: // MANAGER_ACCOUNT_NUMBER
            return MANAGER_ACCOUNT_NUMBER;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.CUSTOMER_ACCOUNT_NUMBER, new org.apache.thrift.meta_data.FieldMetaData("customerAccountNumber", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      tmpMap.put(_Fields.MANAGER_ACCOUNT_NUMBER, new org.apache.thrift.meta_data.FieldMetaData("managerAccountNumber", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(addCustomer_args.class, metaDataMap);
    }

    public addCustomer_args() {
    }

    public addCustomer_args(
      String customerAccountNumber,
      String managerAccountNumber)
    {
      this();
      this.customerAccountNumber = customerAccountNumber;
      this.managerAccountNumber = managerAccountNumber;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public addCustomer_args(addCustomer_args other) {
      if (other.isSetCustomerAccountNumber()) {
        this.customerAccountNumber = other.customerAccountNumber;
      }
      if (other.isSetManagerAccountNumber()) {
        this.managerAccountNumber = other.managerAccountNumber;
      }
    }

    public addCustomer_args deepCopy() {
      return new addCustomer_args(this);
    }

    @Override
    public void clear() {
      this.customerAccountNumber = null;
      this.managerAccountNumber = null;
    }

    public String getCustomerAccountNumber() {
      return this.customerAccountNumber;
    }

    public addCustomer_args setCustomerAccountNumber(String customerAccountNumber) {
      this.customerAccountNumber = customerAccountNumber;
      return this;
    }

    public void unsetCustomerAccountNumber() {
      this.customerAccountNumber = null;
    }

    /** Returns true if field customerAccountNumber is set (has been assigned a value) and false otherwise */
    public boolean isSetCustomerAccountNumber() {
      return this.customerAccountNumber != null;
    }

    public void setCustomerAccountNumberIsSet(boolean value) {
      if (!value) {
        this.customerAccountNumber = null;
      }
    }

    public String getManagerAccountNumber() {
      return this.managerAccountNumber;
    }

    public addCustomer_args setManagerAccountNumber(String managerAccountNumber) {
      this.managerAccountNumber = managerAccountNumber;
      return this;
    }

    public void unsetManagerAccountNumber() {
      this.managerAccountNumber = null;
    }

    /** Returns true if field managerAccountNumber is set (has been assigned a value) and false otherwise */
    public boolean isSetManagerAccountNumber() {
      return this.managerAccountNumber != null;
    }

    public void setManagerAccountNumberIsSet(boolean value) {
      if (!value) {
        this.managerAccountNumber = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case CUSTOMER_ACCOUNT_NUMBER:
        if (value == null) {
          unsetCustomerAccountNumber();
        } else {
          setCustomerAccountNumber((String)value);
        }
        break;

      case MANAGER_ACCOUNT_NUMBER:
        if (value == null) {
          unsetManagerAccountNumber();
        } else {
          setManagerAccountNumber((String)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case CUSTOMER_ACCOUNT_NUMBER:
        return getCustomerAccountNumber();

      case MANAGER_ACCOUNT_NUMBER:
        return getManagerAccountNumber();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case CUSTOMER_ACCOUNT_NUMBER:
        return isSetCustomerAccountNumber();
      case MANAGER_ACCOUNT_NUMBER:
        return isSetManagerAccountNumber();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof addCustomer_args)
        return this.equals((addCustomer_args)that);
      return false;
    }

    public boolean equals(addCustomer_args that) {
      if (that == null)
        return false;

      boolean this_present_customerAccountNumber = true && this.isSetCustomerAccountNumber();
      boolean that_present_customerAccountNumber = true && that.isSetCustomerAccountNumber();
      if (this_present_customerAccountNumber || that_present_customerAccountNumber) {
        if (!(this_present_customerAccountNumber && that_present_customerAccountNumber))
          return false;
        if (!this.customerAccountNumber.equals(that.customerAccountNumber))
          return false;
      }

      boolean this_present_managerAccountNumber = true && this.isSetManagerAccountNumber();
      boolean that_present_managerAccountNumber = true && that.isSetManagerAccountNumber();
      if (this_present_managerAccountNumber || that_present_managerAccountNumber) {
        if (!(this_present_managerAccountNumber && that_present_managerAccountNumber))
          return false;
        if (!this.managerAccountNumber.equals(that.managerAccountNumber))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      List<Object> list = new ArrayList<Object>();

      boolean present_customerAccountNumber = true && (isSetCustomerAccountNumber());
      list.add(present_customerAccountNumber);
      if (present_customerAccountNumber)
        list.add(customerAccountNumber);

      boolean present_managerAccountNumber = true && (isSetManagerAccountNumber());
      list.add(present_managerAccountNumber);
      if (present_managerAccountNumber)
        list.add(managerAccountNumber);

      return list.hashCode();
    }

    @Override
    public int compareTo(addCustomer_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetCustomerAccountNumber()).compareTo(other.isSetCustomerAccountNumber());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetCustomerAccountNumber()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.customerAccountNumber, other.customerAccountNumber);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = Boolean.valueOf(isSetManagerAccountNumber()).compareTo(other.isSetManagerAccountNumber());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetManagerAccountNumber()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.managerAccountNumber, other.managerAccountNumber);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("addCustomer_args(");
      boolean first = true;

      sb.append("customerAccountNumber:");
      if (this.customerAccountNumber == null) {
        sb.append("null");
      } else {
        sb.append(this.customerAccountNumber);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("managerAccountNumber:");
      if (this.managerAccountNumber == null) {
        sb.append("null");
      } else {
        sb.append(this.managerAccountNumber);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class addCustomer_argsStandardSchemeFactory implements SchemeFactory {
      public addCustomer_argsStandardScheme getScheme() {
        return new addCustomer_argsStandardScheme();
      }
    }

    private static class addCustomer_argsStandardScheme extends StandardScheme<addCustomer_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, addCustomer_args struct) throws TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // CUSTOMER_ACCOUNT_NUMBER
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.customerAccountNumber = iprot.readString();
                struct.setCustomerAccountNumberIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 2: // MANAGER_ACCOUNT_NUMBER
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.managerAccountNumber = iprot.readString();
                struct.setManagerAccountNumberIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, addCustomer_args struct) throws TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.customerAccountNumber != null) {
          oprot.writeFieldBegin(CUSTOMER_ACCOUNT_NUMBER_FIELD_DESC);
          oprot.writeString(struct.customerAccountNumber);
          oprot.writeFieldEnd();
        }
        if (struct.managerAccountNumber != null) {
          oprot.writeFieldBegin(MANAGER_ACCOUNT_NUMBER_FIELD_DESC);
          oprot.writeString(struct.managerAccountNumber);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class addCustomer_argsTupleSchemeFactory implements SchemeFactory {
      public addCustomer_argsTupleScheme getScheme() {
        return new addCustomer_argsTupleScheme();
      }
    }

    private static class addCustomer_argsTupleScheme extends TupleScheme<addCustomer_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, addCustomer_args struct) throws TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetCustomerAccountNumber()) {
          optionals.set(0);
        }
        if (struct.isSetManagerAccountNumber()) {
          optionals.set(1);
        }
        oprot.writeBitSet(optionals, 2);
        if (struct.isSetCustomerAccountNumber()) {
          oprot.writeString(struct.customerAccountNumber);
        }
        if (struct.isSetManagerAccountNumber()) {
          oprot.writeString(struct.managerAccountNumber);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, addCustomer_args struct) throws TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(2);
        if (incoming.get(0)) {
          struct.customerAccountNumber = iprot.readString();
          struct.setCustomerAccountNumberIsSet(true);
        }
        if (incoming.get(1)) {
          struct.managerAccountNumber = iprot.readString();
          struct.setManagerAccountNumberIsSet(true);
        }
      }
    }

  }

  public static class addCustomer_result implements org.apache.thrift.TBase<addCustomer_result, addCustomer_result._Fields>, java.io.Serializable, Cloneable, Comparable<addCustomer_result>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("addCustomer_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.STRING, (short)0);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new addCustomer_resultStandardSchemeFactory());
      schemes.put(TupleScheme.class, new addCustomer_resultTupleSchemeFactory());
    }

    public String success; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short)0, "success");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(addCustomer_result.class, metaDataMap);
    }

    public addCustomer_result() {
    }

    public addCustomer_result(
      String success)
    {
      this();
      this.success = success;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public addCustomer_result(addCustomer_result other) {
      if (other.isSetSuccess()) {
        this.success = other.success;
      }
    }

    public addCustomer_result deepCopy() {
      return new addCustomer_result(this);
    }

    @Override
    public void clear() {
      this.success = null;
    }

    public String getSuccess() {
      return this.success;
    }

    public addCustomer_result setSuccess(String success) {
      this.success = success;
      return this;
    }

    public void unsetSuccess() {
      this.success = null;
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return this.success != null;
    }

    public void setSuccessIsSet(boolean value) {
      if (!value) {
        this.success = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((String)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case SUCCESS:
        return getSuccess();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case SUCCESS:
        return isSetSuccess();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof addCustomer_result)
        return this.equals((addCustomer_result)that);
      return false;
    }

    public boolean equals(addCustomer_result that) {
      if (that == null)
        return false;

      boolean this_present_success = true && this.isSetSuccess();
      boolean that_present_success = true && that.isSetSuccess();
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (!this.success.equals(that.success))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      List<Object> list = new ArrayList<Object>();

      boolean present_success = true && (isSetSuccess());
      list.add(present_success);
      if (present_success)
        list.add(success);

      return list.hashCode();
    }

    @Override
    public int compareTo(addCustomer_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetSuccess()).compareTo(other.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, other.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
      }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("addCustomer_result(");
      boolean first = true;

      sb.append("success:");
      if (this.success == null) {
        sb.append("null");
      } else {
        sb.append(this.success);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class addCustomer_resultStandardSchemeFactory implements SchemeFactory {
      public addCustomer_resultStandardScheme getScheme() {
        return new addCustomer_resultStandardScheme();
      }
    }

    private static class addCustomer_resultStandardScheme extends StandardScheme<addCustomer_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, addCustomer_result struct) throws TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 0: // SUCCESS
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.success = iprot.readString();
                struct.setSuccessIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, addCustomer_result struct) throws TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.success != null) {
          oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
          oprot.writeString(struct.success);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class addCustomer_resultTupleSchemeFactory implements SchemeFactory {
      public addCustomer_resultTupleScheme getScheme() {
        return new addCustomer_resultTupleScheme();
      }
    }

    private static class addCustomer_resultTupleScheme extends TupleScheme<addCustomer_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, addCustomer_result struct) throws TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetSuccess()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetSuccess()) {
          oprot.writeString(struct.success);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, addCustomer_result struct) throws TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.success = iprot.readString();
          struct.setSuccessIsSet(true);
        }
      }
    }

  }

  public static class removeCustomer_args implements org.apache.thrift.TBase<removeCustomer_args, removeCustomer_args._Fields>, java.io.Serializable, Cloneable, Comparable<removeCustomer_args>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("removeCustomer_args");

    private static final org.apache.thrift.protocol.TField ACCOUNT_NUMBER_FIELD_DESC = new org.apache.thrift.protocol.TField("accountNumber", org.apache.thrift.protocol.TType.STRING, (short)1);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new removeCustomer_argsStandardSchemeFactory());
      schemes.put(TupleScheme.class, new removeCustomer_argsTupleSchemeFactory());
    }

    public String accountNumber; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      ACCOUNT_NUMBER((short)1, "accountNumber");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // ACCOUNT_NUMBER
            return ACCOUNT_NUMBER;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.ACCOUNT_NUMBER, new org.apache.thrift.meta_data.FieldMetaData("accountNumber", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(removeCustomer_args.class, metaDataMap);
    }

    public removeCustomer_args() {
    }

    public removeCustomer_args(
      String accountNumber)
    {
      this();
      this.accountNumber = accountNumber;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public removeCustomer_args(removeCustomer_args other) {
      if (other.isSetAccountNumber()) {
        this.accountNumber = other.accountNumber;
      }
    }

    public removeCustomer_args deepCopy() {
      return new removeCustomer_args(this);
    }

    @Override
    public void clear() {
      this.accountNumber = null;
    }

    public String getAccountNumber() {
      return this.accountNumber;
    }

    public removeCustomer_args setAccountNumber(String accountNumber) {
      this.accountNumber = accountNumber;
      return this;
    }

    public void unsetAccountNumber() {
      this.accountNumber = null;
    }

    /** Returns true if field accountNumber is set (has been assigned a value) and false otherwise */
    public boolean isSetAccountNumber() {
      return this.accountNumber != null;
    }

    public void setAccountNumberIsSet(boolean value) {
      if (!value) {
        this.accountNumber = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case ACCOUNT_NUMBER:
        if (value == null) {
          unsetAccountNumber();
        } else {
          setAccountNumber((String)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case ACCOUNT_NUMBER:
        return getAccountNumber();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case ACCOUNT_NUMBER:
        return isSetAccountNumber();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof removeCustomer_args)
        return this.equals((removeCustomer_args)that);
      return false;
    }

    public boolean equals(removeCustomer_args that) {
      if (that == null)
        return false;

      boolean this_present_accountNumber = true && this.isSetAccountNumber();
      boolean that_present_accountNumber = true && that.isSetAccountNumber();
      if (this_present_accountNumber || that_present_accountNumber) {
        if (!(this_present_accountNumber && that_present_accountNumber))
          return false;
        if (!this.accountNumber.equals(that.accountNumber))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      List<Object> list = new ArrayList<Object>();

      boolean present_accountNumber = true && (isSetAccountNumber());
      list.add(present_accountNumber);
      if (present_accountNumber)
        list.add(accountNumber);

      return list.hashCode();
    }

    @Override
    public int compareTo(removeCustomer_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetAccountNumber()).compareTo(other.isSetAccountNumber());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetAccountNumber()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.accountNumber, other.accountNumber);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("removeCustomer_args(");
      boolean first = true;

      sb.append("accountNumber:");
      if (this.accountNumber == null) {
        sb.append("null");
      } else {
        sb.append(this.accountNumber);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class removeCustomer_argsStandardSchemeFactory implements SchemeFactory {
      public removeCustomer_argsStandardScheme getScheme() {
        return new removeCustomer_argsStandardScheme();
      }
    }

    private static class removeCustomer_argsStandardScheme extends StandardScheme<removeCustomer_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, removeCustomer_args struct) throws TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // ACCOUNT_NUMBER
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.accountNumber = iprot.readString();
                struct.setAccountNumberIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, removeCustomer_args struct) throws TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.accountNumber != null) {
          oprot.writeFieldBegin(ACCOUNT_NUMBER_FIELD_DESC);
          oprot.writeString(struct.accountNumber);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class removeCustomer_argsTupleSchemeFactory implements SchemeFactory {
      public removeCustomer_argsTupleScheme getScheme() {
        return new removeCustomer_argsTupleScheme();
      }
    }

    private static class removeCustomer_argsTupleScheme extends TupleScheme<removeCustomer_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, removeCustomer_args struct) throws TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetAccountNumber()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetAccountNumber()) {
          oprot.writeString(struct.accountNumber);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, removeCustomer_args struct) throws TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.accountNumber = iprot.readString();
          struct.setAccountNumberIsSet(true);
        }
      }
    }

  }

  public static class removeCustomer_result implements org.apache.thrift.TBase<removeCustomer_result, removeCustomer_result._Fields>, java.io.Serializable, Cloneable, Comparable<removeCustomer_result>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("removeCustomer_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.STRING, (short)0);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new removeCustomer_resultStandardSchemeFactory());
      schemes.put(TupleScheme.class, new removeCustomer_resultTupleSchemeFactory());
    }

    public String success; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short)0, "success");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(removeCustomer_result.class, metaDataMap);
    }

    public removeCustomer_result() {
    }

    public removeCustomer_result(
      String success)
    {
      this();
      this.success = success;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public removeCustomer_result(removeCustomer_result other) {
      if (other.isSetSuccess()) {
        this.success = other.success;
      }
    }

    public removeCustomer_result deepCopy() {
      return new removeCustomer_result(this);
    }

    @Override
    public void clear() {
      this.success = null;
    }

    public String getSuccess() {
      return this.success;
    }

    public removeCustomer_result setSuccess(String success) {
      this.success = success;
      return this;
    }

    public void unsetSuccess() {
      this.success = null;
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return this.success != null;
    }

    public void setSuccessIsSet(boolean value) {
      if (!value) {
        this.success = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((String)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case SUCCESS:
        return getSuccess();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case SUCCESS:
        return isSetSuccess();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof removeCustomer_result)
        return this.equals((removeCustomer_result)that);
      return false;
    }

    public boolean equals(removeCustomer_result that) {
      if (that == null)
        return false;

      boolean this_present_success = true && this.isSetSuccess();
      boolean that_present_success = true && that.isSetSuccess();
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (!this.success.equals(that.success))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      List<Object> list = new ArrayList<Object>();

      boolean present_success = true && (isSetSuccess());
      list.add(present_success);
      if (present_success)
        list.add(success);

      return list.hashCode();
    }

    @Override
    public int compareTo(removeCustomer_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetSuccess()).compareTo(other.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, other.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
      }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("removeCustomer_result(");
      boolean first = true;

      sb.append("success:");
      if (this.success == null) {
        sb.append("null");
      } else {
        sb.append(this.success);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class removeCustomer_resultStandardSchemeFactory implements SchemeFactory {
      public removeCustomer_resultStandardScheme getScheme() {
        return new removeCustomer_resultStandardScheme();
      }
    }

    private static class removeCustomer_resultStandardScheme extends StandardScheme<removeCustomer_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, removeCustomer_result struct) throws TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 0: // SUCCESS
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.success = iprot.readString();
                struct.setSuccessIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, removeCustomer_result struct) throws TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.success != null) {
          oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
          oprot.writeString(struct.success);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class removeCustomer_resultTupleSchemeFactory implements SchemeFactory {
      public removeCustomer_resultTupleScheme getScheme() {
        return new removeCustomer_resultTupleScheme();
      }
    }

    private static class removeCustomer_resultTupleScheme extends TupleScheme<removeCustomer_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, removeCustomer_result struct) throws TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetSuccess()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetSuccess()) {
          oprot.writeString(struct.success);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, removeCustomer_result struct) throws TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.success = iprot.readString();
          struct.setSuccessIsSet(true);
        }
      }
    }

  }

  public static class deposit_args implements org.apache.thrift.TBase<deposit_args, deposit_args._Fields>, java.io.Serializable, Cloneable, Comparable<deposit_args>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("deposit_args");

    private static final org.apache.thrift.protocol.TField ACCOUNT_NUMBER_FIELD_DESC = new org.apache.thrift.protocol.TField("accountNumber", org.apache.thrift.protocol.TType.STRING, (short)1);
    private static final org.apache.thrift.protocol.TField AMOUNT_FIELD_DESC = new org.apache.thrift.protocol.TField("amount", org.apache.thrift.protocol.TType.DOUBLE, (short)2);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new deposit_argsStandardSchemeFactory());
      schemes.put(TupleScheme.class, new deposit_argsTupleSchemeFactory());
    }

    public String accountNumber; // required
    public double amount; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      ACCOUNT_NUMBER((short)1, "accountNumber"),
      AMOUNT((short)2, "amount");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // ACCOUNT_NUMBER
            return ACCOUNT_NUMBER;
          case 2: // AMOUNT
            return AMOUNT;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    private static final int __AMOUNT_ISSET_ID = 0;
    private byte __isset_bitfield = 0;
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.ACCOUNT_NUMBER, new org.apache.thrift.meta_data.FieldMetaData("accountNumber", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      tmpMap.put(_Fields.AMOUNT, new org.apache.thrift.meta_data.FieldMetaData("amount", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(deposit_args.class, metaDataMap);
    }

    public deposit_args() {
    }

    public deposit_args(
      String accountNumber,
      double amount)
    {
      this();
      this.accountNumber = accountNumber;
      this.amount = amount;
      setAmountIsSet(true);
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public deposit_args(deposit_args other) {
      __isset_bitfield = other.__isset_bitfield;
      if (other.isSetAccountNumber()) {
        this.accountNumber = other.accountNumber;
      }
      this.amount = other.amount;
    }

    public deposit_args deepCopy() {
      return new deposit_args(this);
    }

    @Override
    public void clear() {
      this.accountNumber = null;
      setAmountIsSet(false);
      this.amount = 0.0;
    }

    public String getAccountNumber() {
      return this.accountNumber;
    }

    public deposit_args setAccountNumber(String accountNumber) {
      this.accountNumber = accountNumber;
      return this;
    }

    public void unsetAccountNumber() {
      this.accountNumber = null;
    }

    /** Returns true if field accountNumber is set (has been assigned a value) and false otherwise */
    public boolean isSetAccountNumber() {
      return this.accountNumber != null;
    }

    public void setAccountNumberIsSet(boolean value) {
      if (!value) {
        this.accountNumber = null;
      }
    }

    public double getAmount() {
      return this.amount;
    }

    public deposit_args setAmount(double amount) {
      this.amount = amount;
      setAmountIsSet(true);
      return this;
    }

    public void unsetAmount() {
      __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __AMOUNT_ISSET_ID);
    }

    /** Returns true if field amount is set (has been assigned a value) and false otherwise */
    public boolean isSetAmount() {
      return EncodingUtils.testBit(__isset_bitfield, __AMOUNT_ISSET_ID);
    }

    public void setAmountIsSet(boolean value) {
      __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __AMOUNT_ISSET_ID, value);
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case ACCOUNT_NUMBER:
        if (value == null) {
          unsetAccountNumber();
        } else {
          setAccountNumber((String)value);
        }
        break;

      case AMOUNT:
        if (value == null) {
          unsetAmount();
        } else {
          setAmount((Double)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case ACCOUNT_NUMBER:
        return getAccountNumber();

      case AMOUNT:
        return getAmount();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case ACCOUNT_NUMBER:
        return isSetAccountNumber();
      case AMOUNT:
        return isSetAmount();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof deposit_args)
        return this.equals((deposit_args)that);
      return false;
    }

    public boolean equals(deposit_args that) {
      if (that == null)
        return false;

      boolean this_present_accountNumber = true && this.isSetAccountNumber();
      boolean that_present_accountNumber = true && that.isSetAccountNumber();
      if (this_present_accountNumber || that_present_accountNumber) {
        if (!(this_present_accountNumber && that_present_accountNumber))
          return false;
        if (!this.accountNumber.equals(that.accountNumber))
          return false;
      }

      boolean this_present_amount = true;
      boolean that_present_amount = true;
      if (this_present_amount || that_present_amount) {
        if (!(this_present_amount && that_present_amount))
          return false;
        if (this.amount != that.amount)
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      List<Object> list = new ArrayList<Object>();

      boolean present_accountNumber = true && (isSetAccountNumber());
      list.add(present_accountNumber);
      if (present_accountNumber)
        list.add(accountNumber);

      boolean present_amount = true;
      list.add(present_amount);
      if (present_amount)
        list.add(amount);

      return list.hashCode();
    }

    @Override
    public int compareTo(deposit_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetAccountNumber()).compareTo(other.isSetAccountNumber());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetAccountNumber()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.accountNumber, other.accountNumber);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = Boolean.valueOf(isSetAmount()).compareTo(other.isSetAmount());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetAmount()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.amount, other.amount);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("deposit_args(");
      boolean first = true;

      sb.append("accountNumber:");
      if (this.accountNumber == null) {
        sb.append("null");
      } else {
        sb.append(this.accountNumber);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("amount:");
      sb.append(this.amount);
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
        __isset_bitfield = 0;
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class deposit_argsStandardSchemeFactory implements SchemeFactory {
      public deposit_argsStandardScheme getScheme() {
        return new deposit_argsStandardScheme();
      }
    }

    private static class deposit_argsStandardScheme extends StandardScheme<deposit_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, deposit_args struct) throws TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // ACCOUNT_NUMBER
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.accountNumber = iprot.readString();
                struct.setAccountNumberIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 2: // AMOUNT
              if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
                struct.amount = iprot.readDouble();
                struct.setAmountIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, deposit_args struct) throws TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.accountNumber != null) {
          oprot.writeFieldBegin(ACCOUNT_NUMBER_FIELD_DESC);
          oprot.writeString(struct.accountNumber);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldBegin(AMOUNT_FIELD_DESC);
        oprot.writeDouble(struct.amount);
        oprot.writeFieldEnd();
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class deposit_argsTupleSchemeFactory implements SchemeFactory {
      public deposit_argsTupleScheme getScheme() {
        return new deposit_argsTupleScheme();
      }
    }

    private static class deposit_argsTupleScheme extends TupleScheme<deposit_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, deposit_args struct) throws TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetAccountNumber()) {
          optionals.set(0);
        }
        if (struct.isSetAmount()) {
          optionals.set(1);
        }
        oprot.writeBitSet(optionals, 2);
        if (struct.isSetAccountNumber()) {
          oprot.writeString(struct.accountNumber);
        }
        if (struct.isSetAmount()) {
          oprot.writeDouble(struct.amount);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, deposit_args struct) throws TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(2);
        if (incoming.get(0)) {
          struct.accountNumber = iprot.readString();
          struct.setAccountNumberIsSet(true);
        }
        if (incoming.get(1)) {
          struct.amount = iprot.readDouble();
          struct.setAmountIsSet(true);
        }
      }
    }

  }

  public static class deposit_result implements org.apache.thrift.TBase<deposit_result, deposit_result._Fields>, java.io.Serializable, Cloneable, Comparable<deposit_result>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("deposit_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.STRING, (short)0);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new deposit_resultStandardSchemeFactory());
      schemes.put(TupleScheme.class, new deposit_resultTupleSchemeFactory());
    }

    public String success; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short)0, "success");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(deposit_result.class, metaDataMap);
    }

    public deposit_result() {
    }

    public deposit_result(
      String success)
    {
      this();
      this.success = success;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public deposit_result(deposit_result other) {
      if (other.isSetSuccess()) {
        this.success = other.success;
      }
    }

    public deposit_result deepCopy() {
      return new deposit_result(this);
    }

    @Override
    public void clear() {
      this.success = null;
    }

    public String getSuccess() {
      return this.success;
    }

    public deposit_result setSuccess(String success) {
      this.success = success;
      return this;
    }

    public void unsetSuccess() {
      this.success = null;
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return this.success != null;
    }

    public void setSuccessIsSet(boolean value) {
      if (!value) {
        this.success = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((String)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case SUCCESS:
        return getSuccess();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case SUCCESS:
        return isSetSuccess();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof deposit_result)
        return this.equals((deposit_result)that);
      return false;
    }

    public boolean equals(deposit_result that) {
      if (that == null)
        return false;

      boolean this_present_success = true && this.isSetSuccess();
      boolean that_present_success = true && that.isSetSuccess();
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (!this.success.equals(that.success))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      List<Object> list = new ArrayList<Object>();

      boolean present_success = true && (isSetSuccess());
      list.add(present_success);
      if (present_success)
        list.add(success);

      return list.hashCode();
    }

    @Override
    public int compareTo(deposit_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetSuccess()).compareTo(other.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, other.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
      }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("deposit_result(");
      boolean first = true;

      sb.append("success:");
      if (this.success == null) {
        sb.append("null");
      } else {
        sb.append(this.success);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class deposit_resultStandardSchemeFactory implements SchemeFactory {
      public deposit_resultStandardScheme getScheme() {
        return new deposit_resultStandardScheme();
      }
    }

    private static class deposit_resultStandardScheme extends StandardScheme<deposit_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, deposit_result struct) throws TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 0: // SUCCESS
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.success = iprot.readString();
                struct.setSuccessIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, deposit_result struct) throws TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.success != null) {
          oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
          oprot.writeString(struct.success);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class deposit_resultTupleSchemeFactory implements SchemeFactory {
      public deposit_resultTupleScheme getScheme() {
        return new deposit_resultTupleScheme();
      }
    }

    private static class deposit_resultTupleScheme extends TupleScheme<deposit_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, deposit_result struct) throws TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetSuccess()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetSuccess()) {
          oprot.writeString(struct.success);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, deposit_result struct) throws TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.success = iprot.readString();
          struct.setSuccessIsSet(true);
        }
      }
    }

  }

}
